### ISSUE TITLE
Issues with custom tags and u64

### ISSUE THREAD

**Issue by eminence** [BurntSushi/rust-cbor#8]
I can't tell if this is user error, or an issue with rust-cbor.  I'm using `CBorTagEncode` to encode some custom types.   When these custom types include a `u64`, I'm getting an `unexpectedEOF` during decode.

A fully self-contained reproducer is below.   Using `rustc 1.10.0-nightly (4ec5ce5e4 2016-05-12)`

Thanks!

``` rust
extern crate cbor;
extern crate rustc_serialize;

use cbor::{CborTagEncode};
use rustc_serialize::{Decodable, Decoder, Encodable, Encoder};

pub enum TestTypes {
    TestA(u32),
    TestB(u64)
}


fn encode<T: Encodable>(t: &T) -> Vec<u8> {
    let mut e = cbor::Encoder::from_memory();
    e.encode(vec!(t)).unwrap();
    e.into_bytes()
}
fn decode<T: Decodable>(bytes: Vec<u8>) -> T {
    let mut d = cbor::Decoder::from_bytes(bytes);

    let mut items = d.decode();
    let maybe_result = items.next();
    let result = maybe_result.unwrap();
    result.unwrap()
}

impl Encodable for TestTypes {
    fn encode<E: Encoder>(&self, e: &mut E) -> Result<(), E::Error> {
        match self {
            &TestTypes::TestA(ref val) => CborTagEncode::new(100_000_01, val).encode(e),
            &TestTypes::TestB(ref val) => CborTagEncode::new(100_000_02, val).encode(e),
        }
    }
}

impl Decodable for TestTypes {
    fn decode<D: Decoder>(d: &mut D) -> Result<TestTypes, D::Error> {
        let tag = try!(d.read_u64());
        match tag {
            100_000_01 => Ok(TestTypes::TestA(try!(Decodable::decode(d)))),
            100_000_02 => Ok(TestTypes::TestB(try!(Decodable::decode(d)))),
            _ => panic!("Unexpected tag")
        }
    }
}



fn main() {
    let a = TestTypes::TestA(1234u32);
    let b = TestTypes::TestB(1234u64);

    let a_encoded = encode(&a);
    println!("TestA(u32) encoded as {} bytes: {:?}", a_encoded.len(), a_encoded);
    let b_encoded = encode(&b);
    println!("TestB(u64) encoded as {} bytes: {:?}", b_encoded.len(), b_encoded);


    let aa: TestTypes = decode(a_encoded);
    let bb: TestTypes = decode(b_encoded);
}
```

```
achin@bigbox ~/tmp/06/cbor_test $ env RUST_BACKTRACE=1 cargo run
     Running `target/debug/cbor_test`
TestA(u32) encoded as 8 bytes: [218, 0, 152, 150, 129, 25, 4, 210]
TestB(u64) encoded as 8 bytes: [218, 0, 152, 150, 130, 217, 4, 210]

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedEOF', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x55b614483c60 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x55b6144869fb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x55b614486683 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x55b61447de78 - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
   5:     0x55b614486c41 - std::panicking::begin_panic::h4889569716505182
   6:     0x55b61447eaaa - std::panicking::begin_panic_fmt::h484cd47786497f03
   7:     0x55b614486bde - rust_begin_unwind
   8:     0x55b6144bc9ff - core::panicking::panic_fmt::h257ceb0aa351d801
   9:     0x55b614458eb8 - core::result::unwrap_failed::hf334f4fb1663f17e
                        at ../src/libcore/macros.rs:29
  10:     0x55b614475032 - _<std..result..Result<T, E>>::unwrap::h627180c2294af4f7
                        at ../src/libcore/result.rs:723
  11:     0x55b61445ee81 - cbor_test::decode::hf50c8635c0e15470
                        at src/main.rs:24
  12:     0x55b614458a35 - cbor_test::main::h6878392f0e5b8935
                        at src/main.rs:60
  13:     0x55b6144862c8 - std::panicking::try::call::hc5e1f5b484ec7f0e
  14:     0x55b61449079b - __rust_try
  15:     0x55b61449073e - __rust_maybe_catch_panic
  16:     0x55b614485cf3 - std::rt::lang_start::h61f4934e780b4dfc
  17:     0x55b614475109 - main
  18:     0x7f442ddfa61f - __libc_start_main
  19:     0x55b614458528 - _start
  20:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/cbor_test` (exit code: 101)
```

**Comment by eminence** [comment]
I forgot to mention in the original post that the version with `u32` is OK, but the version with `u64` has problems.

**Comment by eminence** [comment]
After poking at this, the issue is in the encoder (not the decoder).   We seem to be hitting the `self.tag` branch in [`fn emit_u64`](https://github.com/BurntSushi/rust-cbor/blob/c4336891b37eab1b0e22edb2d8de8e946a7ccd5f/src/encoder.rs#L174)

**Comment by gavento** [comment]
I just noticed the same bug while digging in the tag code. Thanks for the report!

My minimal example (based on the crate docs) is 
```rust
extern crate cbor;
extern crate rustc_serialize;

use cbor::CborTagEncode;
use rustc_serialize::{Decodable, Decoder, Encodable, Encoder};

struct MyDataStructure {
    pub data: u64,
}

impl Encodable for MyDataStructure {
    fn encode<E: Encoder>(&self, e: &mut E) -> Result<(), E::Error> {
        CborTagEncode::new(43, &self.data).encode(e)
    }
}

fn main() {
    let mut e = ::cbor::Encoder::from_memory();
    e.encode(&[MyDataStructure {data: 42}]);
    println!("{:?}", e.as_bytes());
    for i in e.as_bytes() {
        println!("{:b}", i);
    }
}
```

The problem is that `Encoder::tag` is set *both* when writing the tag and when writing the data inside. 

I would assume that it is enough to change `emit_struct_field` to recognize the special tag and data field and serialize them as such and make `emit_u64` ignore `self.tag` (likely making `Encoder.tag` redundant).

I will try it out.
